### PR TITLE
Add zh-TW translation.

### PR DESCRIPTION
**Pull request by s8321414**
I added zh-TW translation, please review it.

### CODE REVIEW

**Comment by Quicksaver** [comment]
That's great, thanks! But if I could get this through Babelzilla instead I would really appreciate it, as it has many strings for the add-on's AMO listing that aren't here in github, and it's also easier to manage locale updates there. Link: http://www.babelzilla.org/index.php?option=com_wts&Itemid=0&type=show&extension=5684, just register and add yourself as the translator for the add-on; you can reuse these files you've already done there as well so you don't lose anything.

**Comment by s8321414** [comment]
Can you merge this pull request first?I may try babelzilla after this time :smiley:

**Comment by Quicksaver** [comment]
I will add the locale of course, but not through here, I will add it manually as like I mentioned I don't manage the locales through here.

**Comment by s8321414** [comment]
OK,you can close this pull request now,I already work on babelzilla.

**Comment by Quicksaver** [comment]
That's awesome, thanks! :) When you're finished with the translation there, just change its status to "Released", which notifies me automatically about it so that I can include it then.

**Comment by s8321414** [comment]
OK, thanks!

**Comment by s8321414** [comment]
already done here! :smile:

**Comment by Quicksaver** [comment]
Already saw it, thank you so much for your work! I'll include it in the next version. :)

**Comment by s8321414** [comment]
\o/

**Pull request closed without merging**
